# Generated by Django 6.0.3 on 2026-05-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_allocation_roll_number_alter_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='allocation',
            name='roll_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollno_allocation', to='allocation.student'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_allocation', to='allocation.student'),
        ),
    ]
